public class Democlass {
    
    public Integer SumMethod(Integer x,Integer y){
     
        Integer Sum = x + y;
        
        return sum;
        
    }
    public string birthdaymessage(string name, string lastname){
        string message =  name + lastname;
        return message;
    }
    public string indtroduction(string name, string lastname){
        string intro = ' HII My name is '+ name + lastname;
        return intro;
    }

}