public class practiceclass {
 
    public static void practiceclassmethod(){
       Integer a;
        system.debug('This is integer a'+ a);
        a = 50;
        system.debug('This is integer a'+ a);
string b ='vikash';
        system.debug('This is string b'+ b);
      List<Account>acclist =[Select Id,Name from Account Limit 1];
          system.debug('This is list acclist'+ acclist);
        
    }
}