public class publicclasscalculator5 {
    
    
    public Integer cal1(Integer c, Integer x, Integer y){
        Integer z;
        if(c==1){
            z=x+y;
        }else if(c==1){
            z=x-y;
        }else if(c==3){
            z=x*y;
        }else if(c==4){
            z=x/y;
        }
        return z;
    }
    public Integer cal2(Integer c, Integer x, Integer y){
        Integer z;
        if(c==1){
            z=x+y;
        }if(c==1){
            z=x-y;
        }if(c==3){
            z=x*y;
        }if(c==4){
            z=x/y;
        }
        return z;
    }
    
    
    
    


}