public class publicclasscalculator5 {
    public Integer divide (Integer x,Integer y){
        Integer z = x / y;
        return z;
    }
    public Integer add (Integer x,Integer y){
        Integer z = x+y;
        return z;
    }
    public Integer subtract (integer x, integer y){
        integer z = x-y;
return z;
    }
    
    public integer multiply ( integer x, integer y){
        integer z= x*y;
        return z;
    }
    
    Integer t=2;
    Integer i=1;
    public void demo(){
    for (i=1; i<= 10; i++){
        
        System.debug('t *'+i+ '='+ t*i);
    }
    }


}